config/routes.rb
Rails.application.routes.draw do
  root "movies#index"

  resources :characterizations
  resources :genres

  resources :movies do
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end

  resource :session, only: [:new, :create, :destroy]
  get "signin", to: "sessions#new"
  delete "signout", to: "sessions#destroy"

  resources :users
  get "signup", to: "users#new"

  get "movies/filter/:filter", to: "movies#index", as: :filtered_movies
end

app/models/genre.rb
class Genre < ApplicationRecord
  before_save :set_slug

  has_many :characterizations, dependent: :destroy
  has_many :movies, through: :characterizations

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  def to_param
    slug
  end

  private

  def set_slug
    self.slug = name.parameterize
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :require_admin, except: [:index, :show]
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  def index
    @genres = Genre.all
  end

  def show
    @movies = @genre.movies
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to @genre, notice: "Genre successfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      redirect_to @genre, notice: "Genre successfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @genre.destroy
    redirect_to genres_url, status: :see_other, alert: "Genre successfully deleted!"
  end

  private

  def set_genre
    @genre = Genre.find_by!(slug: params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |f| %>
  <%= render 'shared/errors', object: genre %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/genres/edit.html.erb
<%= render 'form', genre: @genre %>

app/views/genres/index.html.erb
<h3>Genre's</h3>
<% @genres.each do |g| %>
  <ul>
    <li><b><%= link_to g.name, g %></b></li>
    <li>Created <%= time_ago_in_words(g.created_at) %> ago</li>
    <li>Updated <%= time_ago_in_words(g.updated_at) %> ago</li>
  </ul>
<% end %>

app/views/genres/new.html.erb
<%= render 'form', genre: @genre %>

app/views/genres/show.html.erb
<h2><%= @genre.name %></h2>

<%= link_to "< All Genres", genres_path %>

<ul>
  <li><b><%= @genre.name %></b></li>
  <li>Created <%= time_ago_in_words(@genre.created_at) %> ago</li>
  <li>Updated <%= time_ago_in_words(@genre.updated_at) %> ago</li>
</ul>

<section>
  <h4>Movies</h4>
  <% @movies.each do |movie| %>
    <div class="details">
      <p>
        <%= link_to movie.title, movie %> &bull; <%= year_of(movie) %>
      </p>
    </div>
  <% end %>
</section>


<% if is_current_user_admin? %>
  <section class="admin">
    <%= link_to "Edit", edit_genre_path(@genre), class: "button" %>
    <%= link_to "Delete", @genre, class: 'button', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  </section>
<% end %>